name: TEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  pull-request-event:
    if: (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]')
    concurrency: test-landscape
    environment: cf_env
    uses: ./.github/workflows/reusable-deploy-workflow.yml@fix-workflow-condition
    secrets:
      CF_API: ${{ secrets.CF_API }}
      CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}
  pull-request-target-event:
    if: (github.event_name == 'pull_request_target') && (github.actor == 'dependabot[bot]')
    concurrency: test-landscape
    environment: cf_env
    uses: ./.github/workflows/reusable-deploy-workflow.yml@fix-workflow-condition
    secrets:
      CF_API: ${{ secrets.CF_API }}
      CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}
